run_dir: "scratch/dev/"
max_concurrent_downloads: 2
is_dev: True
# turn_char_limit: 100
# sampling_n_groups: 4
# sampling_n_per_group: 4
# manual_dates:
#   - "2015-02"
min_year: "2018"
max_year: "2018"
# We will not go beyond 2018-11 (start of .zst)
min_year_min_month: 1
max_year_max_month: 12
all_subreddits:
  - askreddit
  - todayilearned
  - toronto
  - investing
held_out_subreddits:
  - investing